#!/usr/bin/python
import logging
import os
import sys

# so that errors are not sent to stdout
logging.basicConfig(stream=sys.stderr)

sys.path.insert(0, os.path.dirname(__file__))

from NAME import app as application
